### ISSUE TITLE
Don't list members / repos who are not part of the company

### ISSUE THREAD

**Issue by smstuebe** [Zuehlke/zuehlke.github.io#35]
I think we shouldn't list people who aren't working for zuehlke anymore (eg. Michael Borgwardt). BTW: who ensures, that these people are removes when leaving? we have private repos here. (cc: @damphyr )

Also I think we shouldn't list forks (=not our work) (e.g. i18n)

**Comment by xeronimus** [comment]
Thanks for the Input.  the first point was already heavily discussed and the agreement for now is, that we want to keep them.

we will checkout the forks.. thanks

**Comment by xeronimus** [comment]
see #36
